### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by haysclark** [PSPDFKit-labs/jest-measure#4]
https://choosealicense.com/

> [NPM packages](https://libraries.io/search?platforms=NPM) overwhelmingly use the [MIT](https://choosealicense.com/licenses/mit/) or the very similar [ISC](https://choosealicense.com/licenses/isc/) licenses

**Comment by jcampbell05** [comment]
@haysclark  Thank you for reporting this. I've updated this to have a MIT license.
